{% set name = "jupyter_kernel_test" %}
{% set version = "0.4.1" %}
{% set sha256 = "c5ccd0d826e17836815495e5d83bf14ff06ed02923a90affb476e7f7f778f4b9" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/jupyter/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: {{ build }}
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
    - jupyter_client
    - jsonschema
  run:
    - python >=3
    - jupyter_client
    - jsonschema

test:
  imports:
    - jupyter_kernel_test

about:
  home: http://github.com/jupyter/jupyter_kernel_test
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A tool for testing Jupyter kernels
  description: |
    jupyter_kernel_test is a tool for testing Jupyter kernels. It tests
    kernels for successful code execution and conformance with the Jupyter
    Messaging Protocol (currently 5.0).
  doc_url: https://github.com/jupyter/jupyter_kernel_test
  dev_url: https://github.com/jupyter/jupyter_kernel_test

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - takluyver
    - martinRenou
