travis:
  secure:
    BINSTAR_TOKEN: It6CTlTkxfzkzc98Ctd/6ZaOUwQJPkxew8gu+KMLthjqkb3JlblqwptCXHbhIXKmpkCPLVsOPr04ihjRhl15R4Lo7W0/RG0vvgmuArFrHHUwc0h5jtIpVye/J63GvUp4nNYhjybgQjuOZkfzHnVTnHHbYVCJYjYT0nDGQw6ar4mcjBSQZY0dLC4rVZS3MWuCvv2AMvMcHnAGC8QPK4Sb/clCB+ceTGKJ4I3pV9KLVfDjmSK99c5agcxAZLKo4/kzZaPuq1RTKw2S+3oWPRGlf7V6I58x9ddoLRte6i1ZSG4LfVb0xuwULVoTtROO/TWRBlUlwMSbNeu6IltkOAAE1JBWFYYrl/VttzAExbVpboMsWQHydthwbUdEai5RS4KKR6aGCS8WtPumLycGHL7xBK2fvv+gX1GlYTGAh8xMv2di44h2bYtg0yARSanXwI9A+zsdyc5wpBAYtv43t1CmPfJYQUSQv6XbAGjIULfaglpjt39h1LvBpH3N6zTqPhHtM7mlm9q6ggFRMY1Fin334Y+bpx1cR09SHkI7JRH/wl9EXC80L6IUH5cQGyimLY1ExDmiZvccA1EjjOVR3LMIBu5FX39yRpkmvyG3swSBL+Ww4qbhnq756xomiFaVB50suVApWCfVUBTj4TYTRYjOG598fRRb4POSHOhWTp7UZbk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
