travis:
  secure:
    BINSTAR_TOKEN: S/hOzLxo3jKhVCTxiQrdWRd8Yec+APtyCTzcgG1Sezf7uJjkNHzRy4kVF4essJ+YJtsmvxScyYqjY66fAFa+YESyoEY3t7f7r/Ron6fVM/1v25zguIsUSrTaN5NfWGHvkF0LZaxTmHC6JMs4uj9g+xgKREj4EEV07i9EGtFDqde2h/3UWgITZX7kkLfYWDB9zymlDPtLWf7z3g29rrcrPn5dZ/RiW1lAN1MizgZVYcxcA8O92NR+hb8YSt6x6x88kRF+QMkTtZu926VCcwq9CXP5Fd8bITkBqtvA6SaIhTZ3GIZneuOb246Y9A1ejyLFNxFfyJhJ1mm2vBTFU/yHYFD+f2WJ/Pe6+aR+ucH7fDZmmzIlIejDMRZNXDS4AHe4hcP8s7TH7UaLcQ2IPQptAqRo2m8RVN6AGoofFBazJvN0yVllMytRMThxgxlNf7B0jgbm9N0UnP1wGpR36iC/oihKFa4g5+WofKmv254SnXYJoQvej4K1rM3MMzA+rlPfPmm0W0aMrQsy+TdzDnh+8qqgOXCm6143PpF8BuFNJAlhxfWqLdGenwTWl6AANjcIwuUHANWFNO2m70fg9PriKMBrtgJqHkXvvWyqMYaU0KduacFn3JLlqGLiEtrPAhhzhRNWoKUx62w/Cta745R291f9+SqxShCihQoaNp/GPK8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
